# Numpy
_____________

numpy는 벡터 행렬 계산을 효율적으로 처리하기 위한 모듈입니다.

numeric 모듈과 Numarray 모듈이 합쳐져 __높은 수준의 다차원 배열 계산__을 고속 및 효율적으로 처리할 수 있습니다.

numpy 모듈은 pip를 통하여 설치할 수 있습니다.

# Numpy 사용
____

In [1]:
import numpy

상단에 import numpy를 사용하여 numpy를 포함시킵니다.

numpy 함수의 사용방법은 numpy.*를 사용하여 사용이 가능합니다.

In [2]:
import numpy as np

as 구문이 추가될 경우, numpy.* 에서 np.* 으로 축약해서 사용할 수 있습니다.

# numpy 배열 생성
____

In [4]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 3 5]


numpy.array(배열)을 사용하여 numpy 배열을 생성할 수 있습니다.

numpy는 list와 비슷하지만, 배열안에 콤마(,) 가 존재하지 않습니다.

또한, list 형식으로 생성된 배열을 numpy 형식으로 변경할 수 있습니다.

# numpy 배열 복제
____

In [5]:
import numpy as np

a = np.array([1,2,3,4,5])
b = a
c = a.copy()

b[0] = 99

print(a)
print(b)
print(c)

[99  2  3  4  5]
[99  2  3  4  5]
[1 2 3 4 5]


numpy 배열은 list, tuple 등과 동일하게 복사하여 값을 변경할 경우, __원본의 값도 변경됩니다.__

numpy배열.copy()를 통하여 복제할 경우, __원본과 별개의 배열이 생성됩니다.__

# numpy 배열 호출
____

In [6]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(b[2])
print(c[-1])
print(c[0:2])

3
5
[1 3]


list와 동일하게 배열 내의 원소를 대괄호([]) 를 이용하여 호출할 수 있습니다.

# numpy 배열 계산
____

In [7]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(a*2)
print(b*2)
print(c*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[ 3  9 15]


numpy는 list와 다르게 수학 기호를 사용한다면 __각각의 원소로 계산하여 반환합니다.__

list의 경우 *기호 사용시 해당 배열을 이어붙이지만, numpy의 경우 __연산을 실행합니다.__

    * TIP: numpy를 사용할 경우, list comprehension을 사용하지 않아도 원소의 값을 연산할 수 있습니다.